In [1]:
import numpy as np
m = 100000
x = np.random.normal(size = m)
X = x.reshape(-1,1)
y = 4.*x + 3. + np.random.normal(size = m)

# 用批量梯度下降法


In [2]:
def J(Xb, y, theta):
    try:
        return (y - Xb.dot(theta)).T.dot(y - Xb.dot(theta)) / len(y)
    except:
        return float('inf')

def dJ(Xb, y, theta):
    return Xb.T.dot(Xb.dot(theta) - y) * 2 / len(y)

def gradient_descent(Xb, y, init_theta,eta = 0.01,iters = 1e3, epsilon=1e-8):
    theta = init_theta
    i_iters = 0
    while i_iters < iters:
        i_iters += 1
        last_theta = theta
        theta = theta - eta * dJ(Xb, y, theta)
        if abs(J(Xb, y, theta) - J(Xb, y, last_theta)) < epsilon:
            break
    return theta

Xb = np.hstack([np.ones((len(X), 1)), X])
init_theta = np.zeros(Xb.shape[1]) #


In [3]:
%time theta = gradient_descent(Xb, y, init_theta)


CPU times: user 3.32 s, sys: 1.54 s, total: 4.87 s
Wall time: 4.93 s


In [4]:
theta

array([2.99414619, 3.99899034])

In [5]:
def dJ_sgd(Xb_i, y_i, theta):
    return Xb_i.T.dot(Xb_i.dot(theta) - y_i) * 2 

def eta(i_iters):
    t0 = 5
    t1 = 50
    return t0/(i_iters+t1)

def sgd(Xb, y, init_theta,iters):
    theta = init_theta
    i_iters = 0
    while i_iters < iters:
        i = np.random.randint(len(y))
        i_iters += 1
        last_theta = theta
        theta = theta - eta(i_iters) * dJ_sgd(Xb[i,:], y[i], theta)
    return theta

Xb = np.hstack([np.ones((len(X), 1)), X])
init_theta = np.zeros(Xb.shape[1])
iters = len(y)//3

In [6]:
%time theta = sgd(Xb, y, init_theta,iters)

CPU times: user 708 ms, sys: 4 ms, total: 712 ms
Wall time: 728 ms


In [7]:
theta

array([2.99846709, 4.01635792])

由运行结果，批量梯度下降法和随机梯度下降法均能得到较好的回归，然而随机梯度下降法的计算量很小
随机梯度下降法全部的运算次数iters = len(y)//3(其每次迭代只需要计算一个样本,总共计算m//3次),还不到批量下降法一次迭代的运算（一次迭代就需要计算所有的样本（计算m次））次数大


# 封装SGD

对于实际中复杂的数据，为了实现更好的预测性能,我们往往要保证在随机梯度下降法中至少遍历一遍所有的样本。
故将我们上述的sgd函数需改写如下形式

In [8]:
# 此时的iters指的是遍历样本的次数
def sgd(Xb, y, init_theta, iters):
    theta = init_theta
    i_iters = 0
    while i_iters < iters:
        i_iters += 1
        index = np.random.permutation(len(y))
        for i in index:
            theta = theta - eta(i_iters) * dJ_sgd(Xb[i,:], y[i], theta)
    return theta

In [16]:
from regressionProject.LinearRegression import LinearRegression
reg = LinearRegression()
reg.fit_sgd(X,y,iters = 3)

LinearRegression()

In [17]:
reg.coef_

array([4.33605826])

In [18]:
reg.interception_

3.0357940956390683